# Generated by Django 3.0.4 on 2020-04-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
